results_base_dir: 'temp/test/multpleIV'
show_plots: True
#devices: ["A"] # "A","B","C","D","E"
shape: 5000 # ?
input_signal:
  input_signal_type: 'sawtooth'
  time_in_seconds: 5
  direction: 'up'
driver:
  instrument_type: cdaq_to_cdaq
  real_time_rack: False # Driver can be local or remote. Remote for the RT NI Rack (Pinky), and local for the regular one (Brains).
  sampling_frequency: 500
  amplification: 41
  #output_clipping_range: [-4,4] # This value will be multiplied by the amplification value
  instruments_setup: 
    multiple_devices: False
    trigger_source: cDAQ1/segment1
    device:
      activation_instrument: cDAQ1Mod3
      activation_channels: [6,0,1,5,2,4,3] #ao
      activation_voltage_ranges: [[-1.3,0.5],[-0.4,0.6],[-1.4,1],[-1.3,1.3],[-1,0.6],[-0.6,0.3],[-1.2,1.2]] #[[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08]]  
      activation_channel_mask: [1,1,1,1,1,1,1]
      readout_instrument: cDAQ1Mod4
      readout_channels: [0] # ai0
