results_base_dir: 'temp/test/multpleIV'
show_plots: True
devices: ["A"] #,"B","C","D","E"]
shape: 1000 # Number of points to be measured
input_signal:
  input_signal_type: 'sawtooth'
  time_in_seconds: 5
  direction: 'up'
driver:
  instrument_type: cdaq_to_cdaq
  real_time_rack: False # Driver can be local or remote. Remote for the RT NI Rack (Pinky), and local for the regular one (Brains).
  amplification: 41
  inverted_output: True
  instruments_setup: 
    multiple_devices: True
    trigger_source: cDAQ1/segment1
    activation_sampling_frequency: 2000
    readout_sampling_frequency: 10000
    average_io_point_difference: False
    A:
      activation_instrument: cDAQ1Mod3
      activation_channels: [6,0,1,5,2,4,3] #ao
      activation_voltage_ranges: [[-0.9,0.8],[-0.7,1.0],[-0.9,1.1],[-0.8,0.8],[-0.8,0.9],[-0.6,0.5],[-1,1.3]] #[[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08]]  
      activation_channel_mask: [1,1,1,1,1,1,1]
      readout_instrument: cDAQ1Mod4
      readout_channels: [0]
    # B:
    #   activation_instrument: cDAQ1Mod3
    #   activation_channels: [7,8,9,10,11,12,13] #ao
    #   activation_voltage_ranges: [[-0.9,0.5],[-0.3,0.5],[-0.9,0.9],[-1,1],[-0.9,0.6],[-0.6,0.3],[-1,1]] #[[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08]]  
    #   activation_channel_mask: [1,1,1,1,1,1,1]
    #   readout_instrument: cDAQ1Mod4
    #   readout_channels: [1]
    # C:
    #   activation_instrument: cDAQ1Mod1
    #   activation_channels: [6,0,1,5,2,4,3] #ao
    #   activation_voltage_ranges: [[-0.9,0.5],[-0.3,0.5],[-0.9,0.9],[-1,1],[-0.9,0.6],[-0.6,0.3],[-1,1]] #[[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08]]  
    #   activation_channel_mask: [1,1,1,1,1,1,1]
    #   readout_instrument: cDAQ1Mod4
    #   readout_channels: [2]
    # D:
    #   activation_instrument: cDAQ1Mod1
    #   activation_channels: [7,8,9,10,11,12,13] #ao
    #   activation_voltage_ranges: [[-0.9,0.5],[-0.3,0.5],[-0.9,0.9],[-1,1],[-0.9,0.6],[-0.6,0.3],[-1,1]] #[[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08]]  
    #   activation_channel_mask: [1,1,1,1,1,1,1]
    #   readout_instrument: cDAQ1Mod4
    #   readout_channels: [3]
    # E:
    #   activation_instrument: cDAQ1Mod2
    #   activation_channels: [6,0,1,5,2,4,3] #ao
    #   activation_voltage_ranges: [[-0.9,0.5],[-0.3,0.5],[-0.9,0.9],[-1,1],[-0.9,0.6],[-0.6,0.3],[-1,1]] #[[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08],[-0.08,0.08]]  
    #   activation_channel_mask: [1,1,1,1,1,1,1]
    #   readout_instrument: cDAQ1Mod4
    #   readout_channels: [4]
    
