save_dir: tmp/spike_tests/
test_name: spikes_test
repetitions: 1
frequencies: [5000]
data_input_indices: [1, 4]
waveform:
  slope_length: 10
  plateau_length: 10
driver:
  instrument_type: cdaq_to_cdaq
  real_time_rack: False
  instruments_setup: !include ../sampling/instruments/cdaq.yaml # possible options cdaq.yaml, cdaq_rt.yaml, nidaq.yaml, multiple_cdaq.yaml
  amplification: [41]
  # sampling_frequency: 50
  # activation_sampling_frequency: 25000
  # readout_sampling_frequency: 10000
  gain_info: 33.3MOhm
