results_base_dir: tmp/output/conv_model
hyperparameters:
  epochs: 1000
  learning_rate: 1.0e-05
model_structure:
  hidden_sizes:
    - 90
    - 90
    - 90
    - 90
    - 90
  D_in: 7
  D_out: 1
  activation: relu
data:
  postprocessed_data_path: "postprocessed_data.npz"
  steps: 3
  batch_size: 128
  worker_no: 0
  pin_memory: False
  split_percentages:
    - 0.9 # Training data
    - 0.1 # Dev/validation data
    - 0 # Test data
