results_base_dir: tmp/output/conv_model
hyperparameters:
  epochs: 2
  learning_rate: 1.0e-05
model_structure:
  hidden_sizes:
    - 90
    - 90
    - 90
    - 90
    - 90
  D_in: 7
  D_out: 1
  activation: relu
data:
  train_data_path: "/home/unai/Documents/3-Programming/bspy/smg/tmp/data/training/TEST/Brains_testing_2021_05_07_142853/postprocessed_data.npz"
  test_data_path: "/home/unai/Documents/3-Programming/bspy/smg/tmp/data/training/TEST/Brains_testing_2021_05_07_142853/postprocessed_data.npz"
  steps: 3
  batch_size: 128
  worker_no: 0
  pin_memory: False
  split_percentages:
    - 1 # Training data
    - 0 # Dev/validation data
