results_base_dir: tmp/output/new_test_model
hyperparameters:
  epochs: 20
  learning_rate: 1.0e-03
model_architecture:
  hidden_sizes:
    - 90
    - 90
    - 90
    - 90
    - 90
  D_in: 7
  D_out: 1
  activation: relu
data:
  postprocessed_data_path: "/home/unai/Documents/3-Programming/bspy/smg/tmp/postprocessed_data.npz"
  steps: 3
  batch_size: 128
  worker_no: 0
  pin_memory: True
  split_percentages:
    - 0.8 # Training data
    - 0.2 # Dev/validation data
    - 0 # Test data
