results_base_dir: tmp/output/conv_model
hyperparameters:
  epochs: 100
  learning_rate: 1.0e-05
model_structure:
  hidden_sizes:
    - 90
    - 90
    - 90
    - 90
    - 90
  D_in: 7
  D_out: 1
  activation: relu
data:
  dataset_paths: ["C:/Users/Unai/Documents/programming/smg/tmp/data/training/TEST/Brains_testing_2021_07_28_082842_train/postprocessed_data.npz",
                  "C:/Users/Unai/Documents/programming/smg/tmp/data/training/TEST/Brains_testing_2021_07_28_115131_test/postprocessed_data.npz",
                  "C:/Users/Unai/Documents/programming/smg/tmp/data/training/TEST/Brains_testing_2021_07_28_115131_test/postprocessed_data.npz"]
  #test_data_path: "C:/Users/Unai/Documents/programming/smg/tmp/data/training/TEST/Brains_testing_2021_07_28_115131_test/postprocessed_data.npz"
  steps: 3
  batch_size: 128
  worker_no: 0
  pin_memory: False
  split_percentages:
    - 1 # Training data
    - 0 # Dev/validation data
