save_directory: tmp/quick_setup # directory path to save the sampled data
data_name: convolution_nvidia # Please specify a proper name to your sampling measurement.

driver:
  instrument_type: cdaq_to_cdaq

  inverted_output: True # If the amplifier circuitry is inverting amplifier

  instruments_setup: !include instruments/cdaq.yaml # possible options cdaq.yaml, nidaq.yaml, multiple_cdaq.yaml

  amplification: [39.17] # Amplification factor of Amplifier;
  # Maximum/Minimum measured current: +158/-158 nA
  # Maximum/Minimum Op Amp. output voltage: +4/-4 V
  # Amplification equation: abs(Maximum measured current)/abs(Maximum Op. Amp output voltage)
  # Amplification: 158/4 = 39.5
  # Note that amplification value should be re-calculated for each setup seperately.

setup_insights:
  #does not take effect on measurements, for documenting purposes.
  gain_info: 50MOhm # Feedback resistance of Op. Amp; 
  # [6,0,1,5,2,4,3]
  schematic: "\t   ao1   ao6   ao0\n
  \t    #     #     #\n
  \tao3 #           # output\n     
  \t    #     #     #\n
  \t   ao5   ao2   ao4\n"
  setup_name: 'quick'
  device_comments: 'One electrode not working properly.'
  device_material: 'Boron doped silicon'


input_data:
  input_distribution: sawtooth # Desired data shape for data sampling.

  activation_electrode_no: 7 # Number of inputs to the device;
  # activation_electrode_no = #control_electrodes + #input_electrodes

  readout_electrode_no: 1 # Number of output(s) specificed for the device;
  # Note: Multplie output device requires dedicated PCB and setup configuration.

  input_frequency: [2, 3, 5, 7, 13, 17, 19] # Input frequencies;
  # These need to be prime numbers. They will be square rooted and multiplied by factor.

  phase: [-1.9869,  0.6518,  5.7237, -1.3900,  4.1251, -1.5166, -5.2384] # Phase shift in the input signals per activation channel.

  # Amplitude and offset are calculated from the voltage_ranges specified in the driver/instrument_setup configs field.
  # Amplitude: [0.55, 0.95, 0.95, 0.95, 0.95, 0.95, 0.55] # Example
  # Offset: [-0.15,-0.25,-0.25,-0.25,-0.25,-0.25,-0.15] # Example

  ramp_time: 0.4 # Ammount of time used to ramp up to the 

  batch_time: 0.5 #50 # Batch time in seconds. This is used to calculate the batch_size (batch_time * sampling_frequency), 
                # which is, in turn,  used to calculate the total number of samples (total_sample_no * batch_size). 
                # By default 50, with a sampling frequency of 50 Hz. 
                # A standard value to calculate this is: 50*50/activation_frequency
                
  number_batches: 38 # Default value: 3880
