save_directory: tmp/data/training/TEST
data_name: Brains_testing
driver:
  instrument_type: cdaq_to_cdaq
  real_time_rack: False
  instruments_setup: !include instruments/cdaq.yaml # possible options cdaq.yaml, cdaq_rt.yaml, nidaq.yaml, multiple_cdaq.yaml
  amplification: [28.5]
  sampling_frequency: 50
  gain_info: 33.3MOhm
input_data:
  input_distribution: sawtooth
  input_electrodes: 7
  output_electrodes: 1
  input_frequency: [2, 3, 5, 7, 13, 17, 19]
  phase: [-0.57, 0.25, -1.54, 2.17, 0.08, 0.15, -0.65]
  factor: 0.05
  # Amplitude and offset are calculated from the voltage ranges specified in the driver/instrument_setup configs field.
  #amplitude: [0.55, 0.95, 0.95, 0.95, 0.95, 0.95, 0.55]
  #offset: [-0.15,-0.25,-0.25,-0.25,-0.25,-0.25,-0.15] #-0.95
  ramp_time: 0.5
  batch_time: 50
  number_batches: 1
